default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: app_development
  host: <%= ENV['APP_DATABASE_HOST'] || 'postgres' %>
  username: <%= ENV['APP_DATABASE_USERNAME'] || 'postgres' %>
  password: <%= ENV['APP_DATABASE_PASSWORD'] || 'developer' %>

test:
  <<: *default
  database: app_test
  host: <%= ENV['APP_DATABASE_HOST'] || 'postgres' %>
  username: <%= ENV['APP_DATABASE_USERNAME'] || 'postgres' %>
  password: <%= ENV['APP_DATABASE_PASSWORD'] || 'developer' %>

production:
  <<: *default
  database: app_production
